server:
  port: 88

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: yanhuo-auth
          uri: lb://yanhuo-auth  #这里也可以使用地址 http://XXX/xxx
          predicates:
            - Path=/api/auth/**
#          filters:
#            - RewritePath=/api/auth/(?<segment>.*),/auth/$\{segment}
        - id: yanhuo-search
          uri: lb://yanhuo-search
          predicates:
            - Path=/api/search/**
        - id: yanhuo-recommend
          uri: lb://yanhuo-recommend
          predicates:
            - Path=/api/recommend/**
        - id: yanhuo-util
          uri: lb://yanhuo-util
          predicates:
            - Path=/api/util/**
        - id: yanhuo-platform
          uri: lb://yanhuo-platform
          predicates:
            - Path=/api/platform/**